import { db } from "./config";
import { collection, doc, writeBatch } from "firebase/firestore";

// --- 1. LISTA MAESTRA DE MEDICAMENTOS (Limpiada automáticamente) ---
const MEDICAMENTOS_BRUTOS = [
  { "nombre": "CN PARACETAMOL 500 MG, TABLETA" },
  { "nombre": "CN ACETAZOLAMIDA 250 MG. TABLETAS" },
  { "nombre": "CN ACIDO ACETIL SALICILICO 100 MG. T" },
  { "nombre": "CN MICOFENOLATO DE MOFETILO 250" },
  { "nombre": "CN ABACAVIR 600 MG (COMO SULFATO) C" },
  { "nombre": "CN ACICLOVIR 400 MG. TABLETAS O TAB" },
  { "nombre": "CN ACIDO ASCORBICO 500 MG. O ACIDO" },
  { "nombre": "CN ACIDO FOLICO 1 MG, TABLETAS RANU" },
  { "nombre": "CN FOLINATO (COMO SAL CALCICA)15 M" },
  { "nombre": "CN ACITRETINA 25 MG, CÁPSULA." },
  { "nombre": "CN VALPROATO SEMISODICO EQUIVALE" },
  { "nombre": "CN ACIDO URSODEOXICOLICO 250 MG, C" },
  { "nombre": "CN ALFACALCIDOL 0.25 MCG CAPSULAS D" },
  { "nombre": "CN ALFACALCIDOL 1 MCG. CAPSULAS DE" },
  { "nombre": "CN ALOPURINOL 300 MG. TABLETAS." },
  { "nombre": "CN ALUMINIO HIDROXIDO SIN MAGNESI" },
  { "nombre": "CN METOTREXATO 2.5 MG BASE, TABLE" },
  { "nombre": "CN AMIODARONA CLORHIDRATO 200 MG" },
  { "nombre": "CN AMITRIPTILINA CLORHIDRATO 10 M" },
  { "nombre": "CN AMOXICILINA BASE 500 MG, (COMO A" },
  { "nombre": "CN ANASTROZOL 1 MG O LETROZOL 2.5 M" },
  { "nombre": "TR ESTRADIOL VALERIANATO Y ESTRA" },
  { "nombre": "CN ATENOLOL 50 MG. TABLETAS." },
  { "nombre": "CN AZATIOPRINA 50 MG, TABLETA CON" },
  { "nombre": "CN BETANECOL CLORURO 10 MG. TABL" },
  { "nombre": "CN BIPERIDENO HIDROCLORURO 2 MG. T" },
  { "nombre": "CN BROMOCRIPTINA BASE 2.5 MG.(COM" },
  { "nombre": "CN ENALAPRIL MALEATO 20 MG. TABLET" },
  { "nombre": "CN CARBAMAZEPINA 200 MG, TABLETAS." },
  { "nombre": "CN CALCIO IONICO 3OO MG.(EQUIVALEN" },
  { "nombre": "CN CEFALEXINA BASE 500 MG. (COMO M" },
  { "nombre": "CN CIPROFLOXACINO BASE 500 MG (COM" },
  { "nombre": "CN CLARITROMICINA 500 MG TABLETA R" },
  { "nombre": "CN CLORHIDRATO DE CLOMIPRAMINA 25" },
  { "nombre": "CN CLONAZEPAN 2 MG., TABLETAS" },
  { "nombre": "CN CLOMIPRAMINA HIDROCLORURO 75 M" },
  { "nombre": "CN CLORFENAMINA MALEATO 4 MG (SI" },
  { "nombre": "CN CLORPROMAZINA HIDROCLORURO ( E" },
  { "nombre": "CN CLOZAPINA 100 MG. TABLETAS." },
  { "nombre": "CN CODEINA FOSFATO HEMIHIDRATADA" },
  { "nombre": "CN COLCHICINA 0.5 O 0.6 MG. TABLETAS" },
  { "nombre": "CN DAPSONA 100 MG., TABLETAS" },
  { "nombre": "CN DEXAMETASONA 0.5 MG. TABLETAS." },
  { "nombre": "CN DEXTROMETORFANO BROMOHIDRAT" },
  { "nombre": "CN DIAZEPAM 5 MG. TABLETAS RANURAD" },
  { "nombre": "CN DARUNAVIR 600 MG TABLETAS RECU" },
  { "nombre": "CN DOLUTEGRAVIR 50 MG (COMO DOLU" },
  { "nombre": "CN DOLUTEGRAVIR 50 MG (COMO DOLU" },
  { "nombre": "CN DIFENHIDRAMINA CLORHIDRATO 50 M" },
  { "nombre": "CN FENITOINA SODICA 100 MG. DE ACCI" },
  { "nombre": "CN DIGOXINA 0,25 MG, TABLETA" },
  { "nombre": "CN DIMENHIDRINATO 50 MG., TABLETAS" },
  { "nombre": "CN EFAVIRENZ 600 MG, TABLETAS REC" },
  { "nombre": "CN EFAVIRENZ 600 MG, EMTRICITABINA 2" },
  { "nombre": "CN ELVITEGRAVIR 150 MG, COBICISTAT" },
  { "nombre": "CN ENALAPRIL MALEATO 5 MG. TABLETA" },
  { "nombre": "CN ERGOTAMINA TARTRATO 2 MG. O ER" },
  { "nombre": "CN ESPIRONOLACTONA 100 MG. TABLET" },
  { "nombre": "CN ESTROGENOS CONJUGADOS 0.625 M" },
  { "nombre": "CN ALENDRONATO (COMO SAL MONOSOD" },
  { "nombre": "CN FAMOTIDINA 40 MG. TABLETAS O TA" },
  { "nombre": "CN CLORHIDRATO DE FENAZOPIRIDINA 1" },
  { "nombre": "CN FENOBARBITAL 25 MG. TABLETAS RA" },
  { "nombre": "CN FENOBARBITAL 100 MG. TABLETAS R" },
  { "nombre": "CN FLUCONAZOL 200 MG. CAPSULAS O T" },
  { "nombre": "CN FLUOXETINA (COMO CLORHIDRATO) 2" },
  { "nombre": "CN FUROSEMIDA 40 MG., TABS." },
  { "nombre": "CN GABAPENTINA 300 MG. CÁPSULAS." },
  { "nombre": "CN GEMFIBROZILO 600 MG. TABLETA RE" },
  { "nombre": "CN GLIBENCLAMIDA ( NO MICRONIZADA )" },
  { "nombre": "CN GLICLAZIDA 80 MG- TABLETA." },
  { "nombre": "CN NITROGLICERINA 0.5 A 0.6 MG. TABL" },
  { "nombre": "CN HALOPERIDOL 5 MG., TABLETAS" },
  { "nombre": "CN HIDRALAZINA CLORHIDRATO 50 MG. T" },
  { "nombre": "CN HIDROCLOROTIAZIDA 25 MG. TABLE" },
  { "nombre": "CN HIDROCORTISONA 5 MG. TABLETAS." },
  { "nombre": "CN HIDROCORTISONA 20 MG., TABLETA" },
  { "nombre": "CN HIDROXICARBAMIDA 500 MG." },
  { "nombre": "CN HIDROXIZINA CLORHIDRATO25 MG. O" },
  { "nombre": "CN HIDROXICLOROQUINA BASE 310 MG (" },
  { "nombre": "CN ALUMINIO HIDRÓXIDO 200 MG Y MAG" },
  { "nombre": "CN METFORMINA HIDROCLORURO 500 M" },
  { "nombre": "CN HIERRO FUMARATO 200 MG., TABS." },
  { "nombre": "CN BUTILBROMURO DE HIOSCINA 10" },
  { "nombre": "CN OXIBUTININA HIDROCLORURO 5 MG," },
  { "nombre": "CN IBUPROFENO 400 MG. TABLETAS REC" },
  { "nombre": "CN IMIPRAMINA CLORHIDRATO 10 MG. T" },
  { "nombre": "CN IMIPRAMINA CLORHIDRATO 25 MG. T" },
  { "nombre": "CN INDOMETACINA 25 MG., CAPSULAS" },
  { "nombre": "CN ISOSORBIDE DINITRATO 20 MG. TAB" },
  { "nombre": "CN ISOTRETINOÍNA 10 MG . CÁPSULA" },
  { "nombre": "CN ITRACONAZOL 100 MG. CAPSULAS." },
  { "nombre": "CN IVERMECTINA 6 MG. TABLETAS." },
  { "nombre": "CN LAMOTRIGINA 100 MG. TABLETA DIS" },
  { "nombre": "CN LEFLUNOMIDA 20 MG TABLETA" },
  { "nombre": "CN LAMOTRIGINA 25 MG. TABLETA DISP" },
  { "nombre": "CN METILDOPA ( LEVO - ALFA ) 250 MG." },
  { "nombre": "CN METILDOPA 500 MG, TABLETAS RECU" },
  { "nombre": "CN MONTELUKAST 10 MG (COMO MONTE" },
  { "nombre": "CN MONTELUKAST 5 MG, (COMO MONTE" },
  { "nombre": "CN LAMIVUDINA 150 MG. TABLETAS REC" },
  { "nombre": "CN MONTELUKAST 4 MG (COMO MONTEL" },
  { "nombre": "CN LEVODOPA 100 MG. Y CARBIDOPA AN" },
  { "nombre": "CN LEVODOPA 200 MG. Y CARBIDOPA A" },
  { "nombre": "CN LEVOMEPROMAZINA BASE 25 MG (CO" },
  { "nombre": "CN LEVOTIROXINA SODICA 0.025 MG., T" },
  { "nombre": "CN LEVOTIROXINA SODICA 0.10 MG. TAB" },
  { "nombre": "CN LITIO CARBONATO 300 MG. TABLETAS" },
  { "nombre": "CN LOPERAMIDA CLORHIDRATO 2 MG. T" },
  { "nombre": "CN LORAZEPAM 2 MG., TABLETAS" },
  { "nombre": "CN IRBESARTAN 150 MG TABLETA RECUB" },
  { "nombre": "CN LOVASTATINA 20 MG. TABLETAS." },
  { "nombre": "CN ALBENDAZOL 200 MG. TABLETA O TA" },
  { "nombre": "CN MEDROXIPROGESTERONA ACETATO 5" },
  { "nombre": "CN METILFENIDATO HIDROCLORURO 10 M" },
  { "nombre": "CN METOCLOPRAMIDA BASE 10 MG. (CO" },
  { "nombre": "CN MESALAZINA 500 MG (TABLETA DE L" },
  { "nombre": "CN METRONIDAZOL 500 MG. TABLETAS." },
  { "nombre": "CN NEOSTIGMINA BROMURO 15 MG.TAB" },
  { "nombre": "CN AMLODIPINO 5 MG.(COMO BESILATO D" },
  { "nombre": "CN NITROFURANTOINA (MACROCRISTAL" },
  { "nombre": "CJ ANTICONCEPTIVO ORAL EN COMBINA" },
  { "nombre": "CJ ANTICONCEPTIVO ORAL EN COMBINA" },
  { "nombre": "CN OMEPRAZOL 20 MG, CÁPSULA DE LI" },
  { "nombre": "CN OMEPRAZOL 10 MG. CÁPSULA DE LI" },
  { "nombre": "CN PANCREATINA O PANCREALIPASA (1" },
  { "nombre": "CN PANCREALIPASA (4000 UNIDADES F." },
  { "nombre": "CN PERFENAZINA 4 MG. TABLETA RECUB" },
  { "nombre": "CN VITAMINA B-6 ( PIRIDOXINA CLORHI" },
  { "nombre": "CN PIRIMETAMINA 25 MG. TABLETAS." },
  { "nombre": "CN PREDNISOLONA 1 MG., TABLETA" },
  { "nombre": "CN PREDNISOLONA 5 MG, TABLETA" },
  { "nombre": "CN PREDNISOLONA 25 MG., TABLETA" },
  { "nombre": "CN PRIMIDONA 250 MG., TABLETAS" },
  { "nombre": "CN PROPILTIOURACILO 50 MG., TABLETA" },
  { "nombre": "CN PROPRANOLOL CLORHIDRATO 10 MG" },
  { "nombre": "CN PROPRANOLOL CLORHIDRATO 40 MG" },
  { "nombre": "CN RISPERIDONA 1 MILIGRAMO. TABLET" },
  { "nombre": "CN RITONAVIR 100 MG. TABLETAS RECU" },
  { "nombre": "CN SALBUTAMOL ( COMO SULFATO ) 4 M" },
  { "nombre": "CN ALFUZOSINA HIDROCLORURO 10 MG T" },
  { "nombre": "CN SULFASALACINA 500 MG.TABLETAS C" },
  { "nombre": "CN SULINDACO 200 MG.TABLETAS." },
  { "nombre": "CN LORATADINA FEXOFENADINA HIDROCLORURO DE 1" },
  { "nombre": "CN TAMOXIFENO BASE 20 MG. (COMO C" },
  { "nombre": "CN TACROLIMUS 0.5 MG (COMO" },
  { "nombre": "CN TACROLIMUS 1 MG (COMO TACROLIM" },
  { "nombre": "CN TALIDOMIDA 50 MG. CÁPSULAS Ó T" },
  { "nombre": "CN TEOFILINA ANHIDRA 150 MG. TABLET" },
  { "nombre": "CN TEOFILINA ANHIDRA A.P. 250 MG A 3" },
  { "nombre": "CN DOXICICLINA BASE 100 MG. (COMO H" },
  { "nombre": "CN TENOXICAN 20 MG.TABLETAS RECUB" },
  { "nombre": "CN VITAMINA B-1 ( TIAMINA CLORHIDRAT" },
  { "nombre": "CN TOPIRAMATO 100 MG, TABLETA RECU" },
  { "nombre": "CN TIZANIDINA HIDROCLORURO 4 MG . T" },
  { "nombre": "CN TRIFLUOPERAZINA ( COMO DICLORH" },
  { "nombre": "CN TRIMETOPRIMA CON SULFAMETOXAZO" },
  { "nombre": "CN VENLAFAXINA HIDROCLORURO EQUI" },
  { "nombre": "CN VERAPAMILO CLORHIDRATO 80 MG. T" },
  { "nombre": "CN VIGABATRINA 500 MG TABLETA REC" },
  { "nombre": "CN WARFARINA SODICA 1 MG. TABLETA" },
  { "nombre": "CN WARFARINA SODICA 5 MG. TABLETA" },
  { "nombre": "CN CARVEDILOL 6.25 MG, TABLETAS RE" },
  { "nombre": "CN CLOPIDOGREL (COMO BISULFATO) 7" },
  { "nombre": "CN CARVEDILOL 12.5 MG TABLETA O TA" },
  { "nombre": "CN TENOFOVIR DISOPROXIL FUMARATO 3" },
  { "nombre": "CN ACETAMINOFEN 300 MG., SUPOSITO" },
  { "nombre": "TU POLICRESULENO 18 MG-GRAMO. GEL" },
  { "nombre": "CN POLICRESULENO 90 MG. OVULOS DE 3" },
  { "nombre": "TU ÁCIDO SALICÍLICO AL 5% (50 MG/G)" },
  { "nombre": "CN PREPARACION ANTIHEMORROIDAL. F" },
  { "nombre": "TU PREPARACION ANTIHEMORROIDAL, U" },
  { "nombre": "TU BETAMETASONA BASE AL 0.1% (1 MG" },
  { "nombre": "TU BETAMETASONA ( COMO 17 VALERAT" },
  { "nombre": "CN BISACODILO 10 MG. SUPOSITORIOS D" },
  { "nombre": "TU CREMA DE ROSAS. TUBO DE 40 G A 6" },
  { "nombre": "CN DIMENHIDRINATO 25 MG., SUPOSIT" },
  { "nombre": "CN DIMENHIDRINATO 100 MG., SUPOSIT" },
  { "nombre": "TU ESTROGENOS CONJUGADOS F.E.U. 0" },
  { "nombre": "TU FLUOROURACILO 5% (50 MG/G) . CR" },
  { "nombre": "CN GLICEROL (GLICERINA) DE 1 G A 1" },
  { "nombre": "CN GLICEROL (GLICERINA) DE 2 G A 2" },
  { "nombre": "TU HIDROCORTISONA BASE AL .025% (" },
  { "nombre": "TU HIDROCORTISONA BASE AL 1% (10" },
  { "nombre": "CN INDOMETACINA 100 MG., SUPOSITO" },
  { "nombre": "TU LIDOCAÍNA HIDROCLORURO 2% (20 M" },
  { "nombre": "TU JALEA O GEL LUBRICANTE. TUBO CO" },
  { "nombre": "TU FUSIDATO SODICO 2% (20 MG/G). U" },
  { "nombre": "TU OXIDO DE ZINC FÓRMULA. CREMA T" },
  { "nombre": "TU PEROXIDO DE BENZOILO AL 5%. (50 M" },
  { "nombre": "TU SULFADIAZINA DE PLATA AL 1% (10 M" },
  { "nombre": "TU TETRACICLINA CLORHIDRATO AL 1% (" },
  { "nombre": "TU TIOCONAZOL AL 1% (10 MG/GRAMO)" },
  { "nombre": "CN TIOCONAZOL 100 MG. TABLETAS VAG" },
  { "nombre": "AM AGUA ESTERIL PARA INYECCION. AM" },
  { "nombre": "AM ATROPINA SULFATO 0.5 MG/ML. SOL" },
  { "nombre": "AM BIPERIDENO LACTATO 5 MG/ML" },
  { "nombre": "AM GLUCONATO DE CALCIO AL 10 % (1" },
  { "nombre": "FC CEFTRIAXONA BASE 1 G (COMO CEFT" },
  { "nombre": "AM CIMETIDINA BASE 150 MG / ML (COM" },
  { "nombre": "AM CLORFENAMINA MALEATO 1% (10 MG" },
  { "nombre": "AM DEXAMETASONA FOSFATO 4 MG/ ML" },
  { "nombre": "AM DIAZEPAM 10 MG, SOLUCIÓN INYECT" },
  { "nombre": "AM DICLOFENACO SODICO 75 MG. SOLU" },
  { "nombre": "AM FENITOINA SODICA 50 MG / ML. SO" },
  { "nombre": "FA DIMENHIDRINATO SOL., AL 5% FRAS" },
  { "nombre": "AM DOPAMINA CLORHIDRATO 200 MG. (" },
  { "nombre": "AM EPINEFRINA BASE 1 MG / ML. (1:1.0" },
  { "nombre": "UD EPOETINA ALFA (DE ORIGEN ADN RE" },
  { "nombre": "UD EPOETINA ALFA (DE ORIGEN ADN RE" },
  { "nombre": "AM ESTRADIOL VALERATO 10 MG / ML. I" },
  { "nombre": "AM FITOMENADIONA 10 MG/ML. INYECT" },
  { "nombre": "FA FLUFENAZINA DECANOATO 25 MG / M" },
  { "nombre": "AM FUROSEMIDA 20 MG (10 MG / ML) IN" },
  { "nombre": "FA OLANZAPINA 10 MG POLVO LIOFIL" },
  { "nombre": "AM HALOPERIDOL 5 MG/ ML. SOLUCION I" },
  { "nombre": "AM HIDRALAZINA CLORHIDRATO 20 MG. I" },
  { "nombre": "UD ENOXAPARINA SÓDICA 80 MG (8.000" },
  { "nombre": "FA HIDROCORTISONA BASE 100 MG (CO" },
  { "nombre": "FC HIERRO DEXTRANO: SOLUCION COL" },
  { "nombre": "AM BUTILBROMURO DE HIOSCINA 20 MG" },
  { "nombre": "FA INTERFERON BETA 1-A DE ORIGEN AD" },
  { "nombre": "FA INSULINA HUMANA ISÓFANA BIOSINTÉTICA" },
  { "nombre": "FA INSULINA HUMANA CRISTALINA BIOSINTÉTICA" },
  { "nombre": "FC LATANOPROST AL 0,005% (50 UG / ML)" },
  { "nombre": "FC LIDOCAINA CLORHIDRATO AL 2% (2 MG/ML)" },
  { "nombre": "AM MAGNESIO SULFATO AL 20 % (200 MG/ML)" },
  { "nombre": "FA MEDROXIPROGESTERONA ACETATO 150 MG/ML" },
  { "nombre": "FA METILPREDNISOLONA BASE 500 MG (INYECCIÓN)" },
  { "nombre": "AM METOCLOPRAMIDA CLORHIDRATO 10 MG/ML" },
  { "nombre": "AM MORFINA SULFATO PENTAHIDRATO 10 MG/ML" },
  { "nombre": "FA NALOXONA CLORHIDRATO 0.4 MG/ML" },
  { "nombre": "FA ENCILPENICILINA 1.200.000 UNIDADES" },
  { "nombre": "FA BENCILPENICILINA SÓDICA O POTÁSICA" },
  { "nombre": "AM BICARBONATO DE SODIO AL 8.4%" },
  { "nombre": "UD SODIO CLORURO 0.9%. SOLUCIÓN INYECTABLE" },
  { "nombre": "UD SODIO CLORURO 0.9%. SOLUCIÓN INYECTABLE" },
  { "nombre": "AM TESTOSTERONA ENANTATO 250 MG, SOLUCIÓN" },
  { "nombre": "FC VITAMINA B-1 (TIAMINA CLORHIDRATO) 100 MG/ML" }
];

// --- 2. LOGICA DE CARGA (Con Limpieza) ---
export const seedMasterMeds = async () => {
  try {
    const batch = writeBatch(db);
    const medsRef = collection(db, "master_medications");

    MEDICAMENTOS_BRUTOS.forEach((med) => {
      // 1. Limpiamos el nombre: Quitamos "CN ", "TU ", "UD ", etc.
      // Usamos una expresión regular para quitar los primeros 3 caracteres si son seguidos de un espacio
      const nombreLimpio = med.nombre
        .replace(/^(CN|TU|UD|AM|FC|FA|CJ|TR|UD)\s+/, "")
        .trim();

      // 2. Formateamos: Primera letra en mayúscula, resto como venga
      const nombreFinal = nombreLimpio.charAt(0).toUpperCase() + nombreLimpio.slice(1).toLowerCase();

      // 3. Generamos ID amigable
      const id = nombreFinal.toLowerCase().replace(/[^a-z0-9]/g, '-');
      
      const docRef = doc(medsRef, id);
      batch.set(docRef, { nombre: nombreFinal });
    });

    await batch.commit();
    console.log("✅ Lista Maestra de Medicamentos (+200) cargada y limpia.");
  } catch (error) {
    console.error("❌ Error cargando medicamentos:", error);
  }
};

// --- (Opcional) Puedes mantener aquí la seedMasterList de compras si quieres ---
export const seedMasterList = async () => { /* ... ya lo tienes ... */ };